// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentTwo.proto

package org.struggle.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.struggle.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
