// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentTwo.proto

package org.struggle.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.struggle.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
