// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentTwo.proto

package org.struggle.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.struggle.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
